"""
Typographic Model Trainer

Trains a Random Forest classifier on the full receipt-level training
feature set (receipt_dataset_combined_train.csv, produced by
build_receipt_dataset.py's build_multi_dataset(split="train")) to
distinguish clean receipts (label=0) from typographic prompt-injection
attack receipts (label=1). Saves the trained model to
typographic_model.pkl.

This script performs NO internal train/test split. The project has a
dedicated, official held-out test set
(receipt_dataset_combined_test.csv), so every row of the training CSV
is used for fitting the model. All accuracy/precision/recall/F1/ROC
evaluation happens exclusively in evaluate.py against that separate
test set.
"""

import logging
from pathlib import Path

import joblib
import pandas as pd

from sklearn.ensemble import RandomForestClassifier

from config import FEATURE_OUTPUT


logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%H:%M:%S",
    )

__all__ = ["TypographicTrainer"]

MODEL_OUTPUT: Path = FEATURE_OUTPUT / "typographic_model.pkl"

_DROP_COLUMNS: tuple[str, ...] = ("image_name", "dataset", "label")


class TypographicTrainer:
    """
    Trains and persists a Random Forest classifier for typographic
    prompt-injection attack detection, using the full official
    training split (no internal holdout).
    """

    def __init__(self) -> None:

        self.model = RandomForestClassifier(

            n_estimators=200,

            random_state=42,

            n_jobs=-1

        )

    #####################################################

    def load_dataset(self) -> pd.DataFrame:
        """
        Loads the combined multi-dataset training feature set.

        Returns:
            The loaded DataFrame.

        Raises:
            FileNotFoundError: If receipt_dataset_combined_train.csv
                does not exist (i.e. build_receipt_dataset.py's
                build_multi_dataset() has not been run yet).
        """

        dataset_path = FEATURE_OUTPUT / "receipt_dataset_combined_train.csv"

        if not dataset_path.is_file():

            raise FileNotFoundError(
                f"Dataset not found at '{dataset_path}'. Run "
                "build_receipt_dataset.py (build_multi_dataset, "
                "split='train') first."
            )

        logger.info("Loading dataset: %s", dataset_path)

        df = pd.read_csv(dataset_path)

        if df.empty:

            raise ValueError(
                f"Dataset at '{dataset_path}' is empty. Cannot train "
                "on zero samples."
            )

        missing_columns = [
            col for col in ("image_name", "label")
            if col not in df.columns
        ]

        if missing_columns:

            raise ValueError(
                f"Dataset is missing required column(s) "
                f"{missing_columns}. Was it generated by "
                "build_receipt_dataset.py?"
            )

        return df

    #####################################################

    def prepare_data(self, df: pd.DataFrame):
        """
        Splits the training DataFrame into feature matrix X and
        label vector y. No train/test split is performed here — the
        project uses a separate, dedicated test CSV
        (receipt_dataset_combined_test.csv) evaluated by evaluate.py.

        Args:
            df: The full training dataset.

        Returns:
            X, y.

        Raises:
            ValueError: If either class has fewer than 1 sample.
        """

        drop_cols = [c for c in _DROP_COLUMNS if c in df.columns]

        X = df.drop(columns=drop_cols)

        y = df["label"]

        class_counts = y.value_counts()

        if (class_counts < 1).any():

            raise ValueError(
                "Each class needs at least 1 sample to train. Got "
                f"class counts: {class_counts.to_dict()}"
            )

        return X, y

    #####################################################

    def train(self) -> None:
        """
        Loads the official training data, fits the Random Forest on
        the full set, and saves the model to MODEL_OUTPUT.

        No accuracy is computed or returned here — evaluate.py is
        responsible for all metrics, against the dedicated held-out
        test CSV.
        """

        df = self.load_dataset()

        X, y = self.prepare_data(df)

        logger.info(
            "Training Random Forest on %d samples (label "
            "distribution: %s)...",
            len(df),
            y.value_counts().to_dict(),
        )

        self.model.fit(X, y)

        MODEL_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

        joblib.dump(self.model, MODEL_OUTPUT)

        logger.info("Model saved: %s", MODEL_OUTPUT)


##########################################################

if __name__ == "__main__":

    trainer = TypographicTrainer()

    trainer.train()