"""
Typographic Model Trainer

Trains a Random Forest classifier on the receipt-level feature dataset
(receipt_dataset.csv, produced by build_receipt_dataset.py) to
distinguish clean receipts (label=0) from typographic prompt-injection
attack receipts (label=1). Saves the trained model to
typographic_model.pkl for use by evaluate.py and predict.py.
"""

import logging
from pathlib import Path

import joblib
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from config import FEATURE_OUTPUT


logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%H:%M:%S",
    )

__all__ = ["TypographicTrainer"]

MODEL_OUTPUT: Path = FEATURE_OUTPUT / "typographic_model.pkl"

_DROP_COLUMNS: tuple[str, ...] = ("image_name", "label")


class TypographicTrainer:
    """
    Trains and persists a Random Forest classifier for typographic
    prompt-injection attack detection.
    """

    def __init__(self) -> None:

        self.model = RandomForestClassifier(

            n_estimators=200,

            random_state=42,

            n_jobs=-1

        )

    #####################################################

    def load_dataset(self) -> pd.DataFrame:
        """
        Loads the receipt-level feature dataset.

        Returns:
            The loaded DataFrame.

        Raises:
            FileNotFoundError: If receipt_dataset.csv does not exist
                (i.e. build_receipt_dataset.py has not been run yet).
        """

        dataset_path = FEATURE_OUTPUT / "receipt_dataset.csv"

        if not dataset_path.is_file():

            raise FileNotFoundError(
                f"Dataset not found at '{dataset_path}'. Run "
                "build_receipt_dataset.py first."
            )

        logger.info("Loading dataset: %s", dataset_path)

        df = pd.read_csv(dataset_path)

        if df.empty:

            raise ValueError(
                f"Dataset at '{dataset_path}' is empty. Cannot train "
                "on zero samples."
            )

        missing_columns = [
            col for col in _DROP_COLUMNS if col not in df.columns
        ]

        if missing_columns:

            raise ValueError(
                f"Dataset is missing required column(s) "
                f"{missing_columns}. Was it generated by "
                "build_receipt_dataset.py?"
            )

        return df

    #####################################################

    def prepare_data(self, df: pd.DataFrame):
        """
        Splits the dataset into stratified train/test sets.

        Args:
            df: The full receipt-level dataset.

        Returns:
            X_train, X_test, y_train, y_test.

        Raises:
            ValueError: If either class has fewer than 2 samples
                (stratified split is impossible).
        """

        X = df.drop(columns=list(_DROP_COLUMNS))

        y = df["label"]

        class_counts = y.value_counts()

        if (class_counts < 2).any():

            raise ValueError(
                "Each class needs at least 2 samples for a stratified "
                f"train/test split. Got class counts: "
                f"{class_counts.to_dict()}"
            )

        return train_test_split(

            X,

            y,

            test_size=0.2,

            random_state=42,

            stratify=y

        )

    #####################################################

    def train(self) -> float:
        """
        Loads data, trains the Random Forest, evaluates holdout
        accuracy, and saves the model to MODEL_OUTPUT.

        Returns:
            Holdout accuracy score.
        """

        df = self.load_dataset()

        X_train, X_test, y_train, y_test = self.prepare_data(df)

        logger.info("Training Random Forest...")

        self.model.fit(X_train, y_train)

        predictions = self.model.predict(X_test)

        accuracy = accuracy_score(y_test, predictions)

        logger.info("=" * 40)

        logger.info("Accuracy : %.4f", accuracy)

        logger.info("=" * 40)

        MODEL_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

        joblib.dump(self.model, MODEL_OUTPUT)

        logger.info("Model saved: %s", MODEL_OUTPUT)

        return accuracy


##########################################################

if __name__ == "__main__":

    trainer = TypographicTrainer()

    trainer.train()